CREATE PLUGGABLE DATABASE mon_27896_David_ProfitMargin_db
ADMIN USER david IDENTIFIED BY david
FILE_NAME_CONVERT = ('C:\APP\ORADATA\ORCL\PDBSEED\', 
                     'C:\APP\ORADATA\ORCL\MON_27896_DAVID_PROFITMARGIN_DB\');

ALTER PLUGGABLE DATABASE MON_27896_DAVID_PROFITMARGIN_DB SAVE STATE;
