-- Run as SYS or SYSDBA in CDB$ROOT

-- Show current container
SHOW CON_NAME;

-- Open the project PDB 
ALTER PLUGGABLE DATABASE MON_27896_DAVID_PROFITMARGIN_DB OPEN READ WRITE;

-- Switch session into that PDB
ALTER SESSION SET CONTAINER = MON_27896_DAVID_PROFITMARGIN_DB;

-- Confirm
SELECT NAME, OPEN_MODE
FROM   V$PDBS
WHERE  NAME LIKE 'MON_27896_DAVID_PROFITMARGIN%';
